(use-modules (web server))
(use-modules (web request)
	     (web response)
	     (web uri))
(define (request-path-components request)
  (split-and-decode-uri-path (uri-path (request-uri request))))
(define (not-found request) 
  (values (build-response #:code 404) 
	  (string-append "Resource not found: " 
			 (uri-path (request-uri request)))))
(define (hello-hacker-handler request body)
  (cond ((equal? (request-path-components request) '("hacker"))
	 (values '((content-type . (text/plain)))
	      "Hello Hacker!"))
	((equal? (request-path-components request) '("hi"))
	 (values '((content-type . (text/plain)))
		 "Hi!"))
	((equal? (request-path-components request) '("goodbye"))
	 (values '((content-type . (text/plain)))
		 "GoodBye!"))
	((equal? (request-path-components request) '("yes"))
	 (values '((content-type . (text/plain)))
		 "Yes!")))
  not-found)
	
	